dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: nkeDNzpsQcTJJjF6Ywbmr3fPV1yrB34850i4g5D3j7ja9CloohAKekBnoJoBdGcsYNL40+2IKBfCAS8whIS82/SXoTwoAmSG5JYgV/lR+eOdGr+ez2jlusekO/y2Gik6hZJn0ymIORbtHPxYLo5WXN/WCD262KOFN4Yw8aPH+U5cdWkFnQ/pPFEHsoJf3f8dAh3rRop5MPRGHUaDrV9cWG0ZMKqK4sOqlzfsm70fo8l2ZXI3/fExX7nDznSeE0UGqN/XhPdIcS5j3240rLksz0kyqO1ikszp/8IGrNiyDHBi4vOlh4cdzgLutoA9xTQYSS5gL+YfU0vTERmyYQirNJTNOWnlIps4vVFFkLF7O/E1Hj09UnmxTPGnwcRyRMAqtoBa6U/D14Atb0AwzFpGtNkmiFZ4MBUS5rxxie9jN3sZ/VO0GkJa3yn6qDfnk8ut/VifdVbKVA5fA/Ke1EsN50XSHmtPMfDc2dCGTfSD7yg6x7xqLD4huqMyfimZtluKJfVj3I+NjLaBYx6Ts7JuHf90KL2Yw1EcE1K/qZErO1WXxTHLqD0aQGDctgMwo1wr5iAO781sevXdE5N9yr9qDq6CbkmxSKmlK7s0kPVIX9IhmPqGxVAl7fdLzB+4yWVf7g/cSjZt6Oq2QEGLigEwWR4SCa2HjjMr1oKLjDMK2/g=
