dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    secure: aQ2IDNyRkrW0bhdqvdI0BoUDD+eqwc13QbUi9/xIOkC/Vy/1DyIHPCrEJTiUeBLfS0XpDtbb1wq9afLQcFkOLy5tbxN6d+iSNsFof6zHNMFhrj07mMS2U0kxQRyurAdrzcAvqBJsYeWU2XuJmsYtATiQvvEhmFADzJRtBYfMc9B0FRb64S7+3fBgzkTQ5bHpf88uGORoKIlZbbg4off5gzYibiP3mqIiCMQ+UbGtgtnjZvHnGpVmxAmLsvIi8+ZxVfxub5T1LfU9rXUsjF2yYo3rpS9HTFFtx+tTCscNrvFeYyeiirX4FxdIEJEnSvydBQRiDlv3zSiL24GismtySt6IpJylzl5XiCkjZFnWyRITSkWoBjMICHWbDn/qXekSidHkwbJfbg1DyRvVsWokvXAPk5ljtQfPZD70aCVG14re3IRAIMA6KVn9za4FZpzi/IATB9vl6HnunHAkp1EnfLPWGOyuNfZQ/khrYPl5SqaRpRta5jkaB72ECsJfTjo+QJa6Va//MJuJ/19W84VxDobsFVTZysJdmlTIyGrMOGiy3+SLpHhkasgZOIzrKYvjTUMR3qby2eHe7JsEwu4NY1dTwqyuzq+tzgIY/rjtB7/3LFnPTpbUWNfwnAry30rmv73r1gZpgjrhTpeMzZ8IxPU5NsfMgmaQoXEYJWTSiR0=
