dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-09/run.sh |
  bash
notifications:
  slack:
    secure: FKnWkp7QINegqOvdr1Dm1lr9P+4hZ56scrEnH/xSh317p+tiAX992MmPVTazCHCf6Z07bmo8HaLEiNgsXOL8MInHHQyKtgDsfFBvBhFPXLEcIJBzFPZsuYMbr8T41u4nBwezAHQ3KvHPuXPRH+eqxZOtpnzCxBjAxX2qRzGo2zuwYXpy77a9gIrIvl7NpAHJeeV3TroD1LQGpBqJitzyl4g2sKomdxCi2MLMb82ml3mU/WAdEqadBdfXy+GCIwuOLzcL79G9LycH8MzialhVxzrp5ZFMeqqEIprKFd9BdCs4XMPxCbjJsovDJ3rlIAsPLeXuSPaphR6YjVzjp/zfkN5IAYJ1+lnGxLZimTLtCGthSht4BhuyNzjIim+VloOblsTjpw7Miy/Z/NOY0eKBad4WpuAy3BjhZ2GjOhXYiBN6FJCPybtcswoJv9TcoMnUTDZ7Ja0OW6jPS36PUcu2VvdK3zoccUY8bo5CIyZHRBj+4RV6Qt9VTie9Cl4Gdc0/mLNeD+Oao/QAAulfDdo4Km2uZRHqelroPVIUtnFDZILC8d+vg5P2uXOR3c7FbRikrXKk1zT63DgYPDGdVfuZQSqy7fnmKqIzlvqwz2g0k2Szn1ow0ul0MSS8TD9KMVnPitKrZtTFXnFcp8CJQyvd0x1OIQRlUcbforTPuSdkMmM=
